services: 
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    container_name: web
    networks:
      - asa-net

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - asa-net
  dns-jc:
    build:
      context: ./dns-jc
      dockerfile: Dockerfile
    image: dns-jc
    container_name: dns-jc
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    networks:
      - asa-net

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - wordpress
      - wordpress2
    networks:
      - asa-net

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      - asa-net

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - asa-net

  wordpress2:
    image: wordpress
    container_name: wordpress2
    restart: always
    depends_on:
      - db2
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_USER: exampleuser2
      WORDPRESS_DB_PASSWORD: examplepass2
      WORDPRESS_DB_NAME: exampledb2
    volumes:
      - wordpress2:/var/www/html
    networks:
      - asa-net

  db2:
    image: mysql:8.0
    container_name: db2
    restart: always
    environment:
      MYSQL_DATABASE: exampledb2
      MYSQL_USER: exampleuser2
      MYSQL_PASSWORD: examplepass2
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db2:/var/lib/mysql
    networks:
      - asa-net

  postfix:
    build:
      context: ./postfix
      dockerfile: Dockerfile
    image: postfix
    container_name: postfix
    ports:
      - "25:25"
      - "143:143"
      - "993:993"
      - "110:110"
      - "465:465"
      - "587:587"
    networks:
      - asa-net
  
  db3:
    image: mariadb:10.6
    container_name: db3
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db3:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - asa-net

  webmail:
    image: nextcloud
    container_name: webmail
    restart: always

    ports:
      - 8080:80
    links:
      - db3
    volumes:
      - nextcloud:/var/www/html
      - ./webmail/config.php:/var/www/html/config/config.php
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db3
    networks:
      - asa-net

volumes:
  wordpress:
  db:
  wordpress2:
  db2:
  nextcloud:
  db3:


networks:
  asa-net:
    name: asa-net
    driver: bridge

